AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Autorizador - Lambda authorizer
Parameters:
  Environment:
    Description: Environment
    Type: String
  TokenSecretParameterName:
    Description: Token secret parameter name
    Type: String
  TokenTableName:
    Description: Token table name
    Type: String

Resources:  
  AutorizadorLambdaAuthorizerFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: lambda authorizer
      FunctionName: !Join ["_", [!Ref Environment, "escoladesoftware-autorizador-lambdaauthorizerfn"]]
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs18.x
      Timeout: 2
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          TokenSecretParameterName: !Ref TokenSecretParameterName
          TokenTableName: !Ref TokenTableName
    Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: Autorizador
      - Key: Servico
        Value: Lambda

  AutorizadorLambdaAuthorizerLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Environment, "_escoladesoftware-autorizador-lambdaauthorizerfn"]]
      RetentionInDays: 3
      Tags: 
        - Key: Ambiente
          Value: !Ref Environment
        - Key: Microservico
          Value: Autorizador
        - Key: Servico
          Value: LogGroup